# Generated by Django 2.2.10 on 2020-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/home/box/Appstone-Online/BATCH - 1/Django/Django/ecommerce/app/static/img/iphone6.jpeg', upload_to='product/'),
            preserve_default=False,
        ),
    ]
